# Temporary HTTP-only Caddyfile (no SSL)
# Use this if SSL continues to fail

http://praktikoffice.kz {
    encode gzip
    
    # Reverse proxy to static file server on port 3000
    reverse_proxy localhost:3000
    
    # Logging
    log {
        output stdout
        format console
    }
}

http://www.praktikoffice.kz {
    redir http://praktikoffice.kz{uri} permanent
}
