import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import ReactLenis from "lenis/react";
import Cursor from "@/components/cursor";
import { Footer } from "@/components/footer";
import { ColorProvider } from "@/contexts/ColorContext";

const manropeSans = Manrope({
  variable: "--font-manrope-sans",
});

export const metadata: Metadata = {
  title: "Praktik - Smart Office",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manropeSans.variable} antialiased min-h-vh relative`}>
        <ColorProvider>
          <ReactLenis root />
          <Cursor />
          <Navbar />
          {children}
          <Footer />
        </ColorProvider>
      </body>
    </html>
  );
}
